# Familiar Git aliases without the Oh My Zsh runtime.
alias g='git'
alias gst='git status'
alias gaa='git add --all'
alias ga='git add'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gcm='git checkout "$(git_main_branch)"'
alias gfa='git fetch --all --prune --jobs=10'
alias gc='git commit -v'
alias gca='git commit -v --amend'
alias gd='git diff'
alias gds='git diff --staged'
alias gb='git branch'
alias gbd='git branch -d'
alias gl='git pull'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias glo='git log --oneline --decorate --graph -20'
alias grb='git rebase'
alias grbi='git rebase -i'
alias gsta='git stash push'
alias gstp='git stash pop'
alias gsw='git switch'

if (( $+commands[eza] )); then
  alias ls='eza --group-directories-first'
  alias ll='eza -l --git --group-directories-first'
  alias la='eza -la --git --group-directories-first'
  alias lt='eza --tree --level=2 --group-directories-first'
else
  alias ls='ls -G'
  alias ll='ls -lh'
  alias la='ls -lAh'
fi

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias reload='exec zsh'
