"$schema" = "https://starship.rs/config-schema.json"
add_newline = true
palette = "moonlight"
format = "$directory$git_branch$git_status$nodejs$cmd_duration\n$character"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold accent"
read_only = " ro"
read_only_style = "red"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "git:"
style = "magenta"

[git_status]
format = "([$all_status$ahead_behind]($style)) "
style = "yellow"
conflicted = "= "
ahead = "↑${count} "
behind = "↓${count} "
diverged = "↕↑${ahead_count}↓${behind_count} "
untracked = "?${count} "
stashed = "$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = ">${count} "
deleted = "x${count} "

[nodejs]
format = "[node $version]($style) "
style = "green"
detect_extensions = []
detect_files = ["package.json"]
detect_folders = ["node_modules"]

[cmd_duration]
format = "[$duration]($style) "
style = "muted"
min_time = 2000

[character]
success_symbol = "[❯](bold accent)"
error_symbol = "[❯](bold red)"

[palettes.moonlight]
accent = "#82aaff"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
magenta = "#c099ff"
muted = "#636da6"
